_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_mobilenetv3_backbone
    DEPTH: Large
    FEAT_DIM: 1280
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_mobilenet_v3_large
