_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_convnext_backbone
    DEPTH: tiny
    FEAT_DIM: 768
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_convnext_tiny
