_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_inception_resnet_v2_backbone
    FEAT_DIM: 1536
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_inception_resnet_v2
