_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_densenet_backbone
    DEPTH: 121x
    FEAT_DIM: 1024
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_densenet121
