_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_inception_v3_backbone
    FEAT_DIM: 2048
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_inception_v3
