_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_osnet_backbone
    DEPTH: x1_0
    FEAT_DIM: 512
    WITH_IBN: true
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_osnet_ibn_x1_0
