_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_vgg_backbone
    DEPTH: 16x
    FEAT_DIM: 4096
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_vgg16_bn
