_BASE_: ../Base-MGN.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
    WITH_IBN: True
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

# SOLVER:
#   IMS_PER_BATCH: 56

OUTPUT_DIR: logs/dukemtmc/mgn_S50_ibn
