_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_inception_v3_backbone
    FEAT_DIM: 2048
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/bagtricks_inception_v3
