_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_osnet_backbone
    DEPTH: x1_0
    FEAT_DIM: 512
    WITH_IBN: true
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/bagtricks_osnet_ibn_x1_0
