_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_vgg_backbone
    DEPTH: 16x
    FEAT_DIM: 4096
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/bagtricks_vgg16_bn
