_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_mobilenetv3_backbone
    DEPTH: Large
    FEAT_DIM: 1280
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/bagtricks_mobilenet_v3_large
