_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_convnext_backbone
    DEPTH: tiny
    FEAT_DIM: 768
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/bagtricks_convnext_tiny
