_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    WITH_SE: True
    PRETRAIN_PATH: /home/lhw/.cache/torch/hub/checkpoints/seresnet50_ra_224-8efdb4bb.pth
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/bagtricks_SeR50
