_BASE_: ../Base-MGN-AGW.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
    WITH_IBN: False
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

# SOLVER:
#   IMS_PER_BATCH: 56

OUTPUT_DIR: logs/msmt17/mgn_agw_S50
